; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:keylamp]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino

; specify the serial device for your Nano/FTDI adapter
upload_port = /dev/ttyUSB0
; most Pro Mini/FTDI bootloaders use 57600 baud; if yours is new you can bump
; this to 115200, but 57600 is safest to avoid "not in sync" errors
upload_speed = 57600


; add libraries used by the sketch
lib_deps = 
	FastLED@^3.5.0

; optimize size
build_flags = -Os -flto=full